##############################################################################
######			USEFUL DOCKER COMMANDS:
######
######		- docker build -t myshop-img -f Dockerfile .
######		- docker run -p 9980:80 -p 3380:3306 --name=myshop -d myshop-img
######		- docker exec -it mule-ce /bin/bash
######		- Per svuotare la cache: docker builder prune
######		- Per elencare i volumi: docker volume ls
######
##############################################################################
# 

######################## CONFIGURAZIONE ####################################


#############################################################


###### Start from  ######
FROM php:7.4.3-apache


# Update and install packages
RUN apt-get update && apt-get install

RUN apt-get install -y \
	vim \
	git \
	bash-completion \
	libxml2-dev \
	

RUN docker-php-ext-install mysqli \
	docker-php-ext-install soap \
	a2enmod rewrite

# Copy temp files.
COPY createUserAndDatabase.sql /tmp/createUserAndDatabase.sql
COPY configureWP.sql /tmp/configureWP.sql

# Copy source code and scripts.
COPY startServicesScript.sh /root/startServicesScript.sh

COPY wp-config.php /var/www/html/
COPY SRC/db_wp_edizioni_stage.2021-10-11.sql /tmp/db_wp_edizioni_stage.2021-10-11.sql

# Install mariadb, create and init the database.
RUN apt-get install -y mariadb-server  && \
	/usr/sbin/service mysql start && \
	mysql < /tmp/createUserAndDatabase.sql && \
	mysql wp_edizioni < /tmp/db_wp_edizioni_stage.2021-10-11.sql && \
	mysql wp_edizioni < /tmp/configureWP.sql

# Copy the code of the plugin.
RUN git clone --branch dev https://github.com/ScuolaNormaleSuperiore/wp-pagopa-gateway-cineca.git /var/www/html/wp-content/plugins/wp-pagopa-gateway-cineca

# Remove the temp file.
RUN rm -rf /tmp/*

EXPOSE 9980 3380

######  Start Server Services with the bash shell ######
ENTRYPOINT ["/bin/bash"]
CMD ["/root/startServicesScript.sh"]
